Your name: 楊元福 108003817

## Hi, welcome to Colab

https://colab.research.google.com/notebooks/intro.ipynb

The ways to programming Python code have 2, format of .py and .ipynb

And here is the format of I Python Notebook (.ipynb)

The difference between these two is that ipy is written in the cells

And every cell can be Code or Text

In [1]:
print("I'm a code cell")

I'm a code cell


I'm a Text Cell

The memory of each cell is same.

See the following example:

In [2]:
x = 10
a = 5

In [3]:
print(x+a)

15


Even you delete a cell, the code you ran still be remembered

<a href="https://www.youtube.com/watch?v=inN8seMm7UI">Colab Demo Video</a>

You can run the code cell by clicking the button on the left of the cell or press "shift" + "enter"

In [4]:
seconds_in_a_day = 24 * 60 * 60
seconds_in_a_day

86400

In [5]:
seconds_in_a_week = 7 * seconds_in_a_day
seconds_in_a_week

604800

**recommend you to see this tutorial then learn python, colab, numpy**
*https://colab.research.google.com/github/cs231n/cs231n.github.io/blob/master/python-colab.ipynb*

About where you can start Python:
https://docs.python.org/3/tutorial/

Where you can start Numpy: https://numpy.org/doc/stable/user/quickstart.html


## Test your Python skill

1. (Example) print a number which mutiple by a=2 and b=4:

In [6]:
a=2
b=4
print(a*b)

8


expected output: 8

Now try to follow the instructions to complete codes below

if need more python tutorials:https://www.codecademy.com/learn/learn-python

In [8]:
# create two viables a and b that is 2 and 4 respectively
a=2
b=4

def equal_self(x,y):
  TF=False
  if y/x == x:
    TF=True
  return TF

# print the output of the function "equal_self" by input a,b
print(equal_self(a,b))

True


expect output: True

In [9]:
x = [1,2,3]
#output the length of x
print(len(x))

3


expect output: 3

## Numpy Test

In [10]:
# please import the numpy library and call it np
import numpy as np

In [12]:
# give a array with zeros in 3*2
np.zeros((3,2), float)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

expected output:

```
array([[ 0.,  0.],
   [ 0.,  0.],       
   [ 0.,  0.]])
```



In [13]:
arr = np.linspace(0,19,20)
# output the sum of arr
print(arr.sum())

190.0


expected output: 190.0

In [14]:
# output the shape of arr
arr.shape

(20,)

expected output: (20,)

In [15]:
# output the reshaped arr to (4,5)
arr.reshape(4,5)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

expected output:

```
array([[ 0., 1., 2., 3., 4.],
   [  5., 6., 7., 8., 9.],
   [10., 11., 12., 13., 14.],
   [15., 16., 17., 18., 19.]])
```



In [16]:
# output the shape of arr
arr.shape

(20,)

expected output: (4, 5)

In [17]:
# output the maximum number of arr
arr.max()

19.0

expected output: 19.0